#define MAINPREFIX ik
#define PREFIX kh
#define PREFIX_BEAUTIFIED Kreepy's Helpers

#include "script_version.hpp"
#define VERSION MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCH
#define VERSION_AR MAJOR,MINOR,PATCH
#define REQUIRED_VERSION VERSION

#define AUTHOR QUOTE(Im Kreepy)

#ifndef COMPONENT_BEAUTIFIED
    #define COMPONENT_BEAUTIFIED COMPONENT
#endif
#ifdef SUBCOMPONENT_BEAUTIFIED
    #define COMPONENT_INFO PREFIX_BEAUTIFIED - COMPONENT_BEAUTIFIED - SUBCOMPONENT_BEAUTIFIED
#else
    #define COMPONENT_INFO PREFIX_BEAUTIFIED - COMPONENT_BEAUTIFIED
#endif
#define COMPONENT_NAME QUOTE(COMPONENT_INFO)
